### PR TITLE
added South (east coast) 15 parks

### PR DESCRIPTION
**Pull request by burmanp**

### CODE REVIEW

**Comment by burmanp** [comment]
Any problem or change required, please let me know?

**Review by OozyGrub — CHANGES_REQUESTED** [review]
east coast is missing 1 park. you added 14 parks out of 15 parks. @burmanp

**Comment by burmanp** [comment]
> 

Added

**Review by OozyGrub — APPROVED** [review]

**Comment by OozyGrub** [comment]
Thanks for your hard work on this. @burmanp

**Pull request merged**
